_target_: src.data.data_modules.SVHNDataModule
paths:
  root: ${hydra:runtime.cwd}/datasets
batch_size: 128
num_workers: 7
pin_memory: true
persistent_workers: true

input_shape: [3, 32, 32]
normalize:
  mean: [0.4377, 0.4438, 0.4728]
  std: [0.1980, 0.2010, 0.1970]
