_target_: src.data.data_modules.CIFAR10DataModule
paths:
  root: ./tests/assets/dummy_dataset
batch_size: 4
num_workers: 7
pin_memory: false
persistent_workers: false

input_shape: [3, 32, 32]
normalize:
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]
