# @package _group_
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42

direction: minimize
study_name: cifar10_optuna
storage: null
n_trials: 50
n_jobs: 1