# conf/hydra/sweeper/optuna_sweeper.yaml
# @package hydra.sweeper
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42

direction: minimize
study_name: cifar10_optuna
storage: null
n_trials: 30
n_jobs: 1

search_space: null
custom_search_space: null

params:
  model.growth_rate: choice(12,16,24)
  model.drop_prob: choice(0.0,0.1,0.2)
  model.compression_factor: choice(0.4,0.5,0.6)
  optimizer.lr: tag(log, interval(1e-4,1e-1))
  optimizer.weight_decay: tag(log, interval(1e-6,1e-3))
  dataset.batch_size: choice(64,128,256)